# ── Entorn de staging (GitHub Pages) ─────────────────────────────────────────
# S'usa amb `hugo --environment staging`
# o automàticament al GitHub Actions workflow

baseURL = "https://112books.github.io/guiesbarcelona-elglobusvermell/"

enableRobotsTXT = true

[params]
  env = "staging"
